version: '2'
services:
  nginx:
    image: nginx
    depends_on:
      - "php"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /usr/local/docker_nmp/conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /usr/local/docker_nmp/conf/nginx/conf.d:/etc/nginx/conf.d
      - /usr/local/docker_nmp/www:/usr/share/nginx/html
    container_name: "X-nginx"  
  php:
    build: ./
    volumes:
      - /usr/local/docker_nmp/www:/var/www
      - /usr/local/docker_nmp/conf/php/php.ini:/usr/local/etc/php/php.ini
      - /usr/local/docker_nmp/conf/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
    container_name: "X-php"
  mysql:
    image: mysql
    volumes:
      - /usr/local/docker_nmp/mysqldata:/var/lib/mysql
      - /usr/local/docker_nmp/conf/mysql/my.cnf:/etc/mysql/conf.d/mysql.cnf
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    container_name: "X-mysql"  
